
#logging:
#  level:
#    org:
#      hibernate:
#        SQL: DEBUG
#        type: TRACE
#spring:
#  datasource:
#    url: postgres://rgbqjbrqvtdfak:b5ea05e5fa8866109490ef24e93355ab82b57da340601c8a711f1eea4fce0a11@ec2-54-156-149-189.compute-1.amazonaws.com:5432/dae37jvms5dmk7
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#springdoc:
#  api-docs:
#    path: /yupana-api-docs
#  swagger-ui:
#    path: /yupana-api-docs-ui.html
#propiedas del archivo
# PostgreSQL
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/yup
    username: postgres
    password: postgres
 #para el file
  servlet:
       multipart:
         max-file-size: 10MB
         max-request-size: 10MB
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc.lob.non_contextual_creation: true
  #Configuracion del SMTP GMAIL
  mail:
    host: smtp.gmail.com
    port: 587 
    username: yupanaservice@gmail.com
    password: yupana123
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls.enable: true
   # Fin de configuracion del SMTP GMAL 
   #File
 
   
server:
  port: 8088
  
 